//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YIYUNEntities15 : DbContext
    {
        public YIYUNEntities15()
            : base("name=YIYUNEntities15")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Buyjl> Buyjl { get; set; }
        public DbSet<MVtype> MVtype { get; set; }
        public DbSet<Singer> Singer { get; set; }
        public DbSet<SingerLX> SingerLX { get; set; }
        public DbSet<SingerRD> SingerRD { get; set; }
        public DbSet<Song> Song { get; set; }
        public DbSet<Songlist> Songlist { get; set; }
        public DbSet<Songlistss> Songlistss { get; set; }
        public DbSet<SongRD> SongRD { get; set; }
        public DbSet<Songtype> Songtype { get; set; }
        public DbSet<Userjl> Userjl { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UserSinger> UserSinger { get; set; }
        public DbSet<Zhuanj> Zhuanj { get; set; }
    }
}
