//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int gqid { get; set; }
        public int zjid { get; set; }
        public string gqimg { get; set; }
        public string js { get; set; }
        public Nullable<int> jb { get; set; }
        public string jbtest { get; set; }
        public string gqname { get; set; }
        public Nullable<int> picedq { get; set; }
        public Nullable<int> typeid { get; set; }
        public string texts { get; set; }
        public string sc { get; set; }
        public System.DateTime times { get; set; }
        public int gsid { get; set; }
        public int userid { get; set; }
        public string mp3 { get; set; }
    }
}
