//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zhuanj
    {
        public int zjid { get; set; }
        public int gsid { get; set; }
        public string zjname { get; set; }
        public int picezj { get; set; }
        public int zjhot { get; set; }
        public string Zhuanjimg { get; set; }
        public Nullable<decimal> gqmoney { get; set; }
    }
}
